name: expense_tracker_chatgpt
description: Offline Expense Tracker by ChatGPT - Dark theme
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  sqflite: ^2.2.8
  path_provider: ^2.0.14
  intl: ^0.18.1
  fl_chart: ^0.60.0
  flutter_slidable: ^2.0.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png